name: Release

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: finsweet/workflow-release/.github/workflows/release.yml@main
    secrets: inherit
